# Generated by Django 5.0.6 on 2025-01-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournamentregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('team_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('captain_name', models.CharField(max_length=150)),
                ('manager_name', models.CharField(max_length=150)),
                ('one_player', models.CharField(max_length=150)),
                ('two_player', models.CharField(max_length=150)),
                ('three_player', models.CharField(max_length=150)),
                ('four_player', models.CharField(max_length=150)),
                ('five_player', models.CharField(max_length=150)),
                ('six_player', models.CharField(max_length=150)),
                ('seven_player', models.CharField(max_length=150)),
                ('eight_player', models.CharField(max_length=150)),
                ('jersey_color', models.CharField(max_length=150)),
                ('coach_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('playing_hours', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('booked_at', models.DateField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.customer')),
            ],
        ),
    ]
