# Generated by Django 5.0.6 on 2025-02-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='court_number',
            field=models.CharField(choices=[('1', 'Premium Court'), ('2', 'Gold Court'), ('3', 'Silver Court')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('court_number', 'time', 'date')},
        ),
    ]
